package global.configuration.jooq.tables;


import javax.annotation.Generated;

import global.configuration.jooq.tables.Account;
import global.configuration.jooq.tables.Customer;
import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>PUBLIC</code> schema.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.11.11"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index PRIMARY_KEY_A = Indexes0.PRIMARY_KEY_A;
    public static final Index PRIMARY_KEY_C = Indexes0.PRIMARY_KEY_C;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index PRIMARY_KEY_A = Internal.createIndex("PRIMARY_KEY_A", Account.ACCOUNT, new OrderField[] { Account.ACCOUNT.ID }, true);
        public static Index PRIMARY_KEY_C = Internal.createIndex("PRIMARY_KEY_C", Customer.CUSTOMER, new OrderField[] { Customer.CUSTOMER.ID }, true);
    }
}
