package global.configuration.jooq.tables;

import javax.annotation.Generated;

/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.11.11"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.account</code>.
     */
    public static final Account ACCOUNT = global.configuration.jooq.tables.Account.ACCOUNT;

    /**
     * The table <code>PUBLIC.customer</code>.
     */
    public static final Customer CUSTOMER = global.configuration.jooq.tables.Customer.CUSTOMER;


}

