package global.configuration.jooq.records;


import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import global.configuration.jooq.tables.Transaction;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.11.11"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TransactionRecord extends UpdatableRecordImpl<TransactionRecord> implements Record7<Long, Long, Long, BigDecimal, String, Timestamp, String> {

    private static final long serialVersionUID = 1695125446;
    /**
     * Setter for <code>PUBLIC.transaction.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.transaction.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>PUBLIC.transaction.sender_account</code>.
     */
    public void setSenderAccount(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.transaction.sender_account</code>.
     */
    public Long getSenderAccount() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>PUBLIC.transaction.receiver_account</code>.
     */
    public void setReceiverAccount(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.transaction.receiver_account</code>.
     */
    public Long getReceiverAccount() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>PUBLIC.transaction.amount</code>.
     */
    public void setAmount(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.transaction.amount</code>.
     */
    public BigDecimal getAmount() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>PUBLIC.transaction.currency</code>.
     */
    public void setCurrency(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>PUBLIC.transaction.currency</code>.
     */
    public String getCurrency() {
        return (String) get(4);
    }

    /**
     * Setter for <code>PUBLIC.transaction.date_time</code>.
     */
    public void setDateTime(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>PUBLIC.transaction.date_time</code>.
     */
    public Timestamp getDateTime() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>PUBLIC.transaction.transaction_id</code>.
     */
    public void setTransactionId(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>PUBLIC.transaction.transaction_id</code>.
     */
    public String getTransactionId() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, Long, Long, BigDecimal, String, Timestamp, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, Long, Long, BigDecimal, String, Timestamp, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Transaction.TRANSACTION.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return Transaction.TRANSACTION.SENDER_ACCOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return Transaction.TRANSACTION.RECEIVER_ACCOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field4() {
        return Transaction.TRANSACTION.AMOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Transaction.TRANSACTION.CURRENCY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return Transaction.TRANSACTION.DATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Transaction.TRANSACTION.TRANSACTION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getSenderAccount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component3() {
        return getReceiverAccount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component4() {
        return getAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getCurrency();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getDateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getTransactionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getSenderAccount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getReceiverAccount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value4() {
        return getAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getCurrency();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getDateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getTransactionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransactionRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransactionRecord value2(Long value) {
        setSenderAccount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransactionRecord value3(Long value) {
        setReceiverAccount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransactionRecord value4(BigDecimal value) {
        setAmount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransactionRecord value5(String value) {
        setCurrency(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransactionRecord value6(Timestamp value) {
        setDateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransactionRecord value7(String value) {
        setTransactionId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransactionRecord values(Long value1, Long value2, Long value3, BigDecimal value4, String value5, Timestamp value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached transactionRecord
     */
    public TransactionRecord() {
        super(Transaction.TRANSACTION);
    }

    /**
     * Create a detached, initialised transactionRecord
     */
    public TransactionRecord(Long id, Long originAccount, Long destinationAccount, BigDecimal amount, String currency, Timestamp dateTime, String transactionId) {
        super(Transaction.TRANSACTION);

        set(0, id);
        set(1, originAccount);
        set(2, destinationAccount);
        set(3, amount);
        set(4, currency);
        set(5, dateTime);
        set(6, transactionId);
    }
}

